<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mz</string>
	</array>
	<key>name</key>
	<string>Maze</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Wall</string>
			<key>match</key>
			<string>##|``</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Path</string>
			<key>match</key>
			<string>\.\.</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Splitter</string>
			<key>match</key>
			<string>&lt;&gt;</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Signal</string>
			<key>match</key>
			<string>\*[\*A-Za-z0-9]</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Pause</string>
			<key>match</key>
			<string>[0-9]{2}</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Start</string>
			<key>match</key>
			<string>\^\^</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hole</string>
			<key>match</key>
			<string>\(\)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Out</string>
			<key>match</key>
			<string>&gt;&gt;</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>In</string>
			<key>match</key>
			<string>&lt;&lt;</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>One use</string>
			<key>match</key>
			<string>--</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Direction</string>
			<key>match</key>
			<string>%[LRUDNlrudn]</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Assignment function</string>
			<key>match</key>
			<string>([A-Za-z][A-Za-z0-9]) *-&gt; *(([-+*/]=) *([0-9]+)|(=) *(([0-9]+)|("[^"]*")|('[^']*')))</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Equality Function</string>
			<key>match</key>
			<string>([A-Za-z][A-Za-z0-9]) *-&gt; *(?:IF|if) *([&lt;&gt;]=?|==|\*[\*A-Za-z0-9]) *(?:THEN|then) *(%[LRUDNlrudn]) *(?:ELSE|else) *(%[LRUDNlrudn])</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function cell</string>
			<key>match</key>
			<string>[A-Za-z][A-Za-z0-9]</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string> *//.*</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.maze</string>
	<key>uuid</key>
	<string>178833ea-fbf9-43f8-a9f9-cda1daae8be6</string>
</dict>
</plist>
